blog_post/urls.py
from django.contrib import admin
from django.urls import path,include
from post import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('post/',include('post.urls')),
    path('user/',include("user.urls")),
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

post/urls.py
from django.urls import path
from . import views
app_name='post'


urlpatterns = [
    path('',views.post,name='post'),
    path('dashboard/',views.dashboard,name='dashboard'),
    path('addPost/',views.addPost,name='addpost'),
    path('post/<slug:slug>/',views.detail,name='detail'),
    path('update/<slug:slug>/',views.update,name='update'),
    path('delete/<slug:slug>/',views.delete,name='delete'),
    path('comment/<slug:slug>',views.addCommit,name='comment'),
]

user/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='user'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.loginUser,name='login'),
    path('logout/',views.logoutUser,name='logout'),
]

post/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
# Create your models here.


class Post(models.Model):
    author=models.ForeignKey(User,on_delete=models.CASCADE)
    title=models.CharField('Title', max_length=50)
    content=RichTextField()
    created_date = models.DateTimeField(auto_now_add=True,verbose_name="Yaratilgan vaqti")
    post_image = models.FileField(blank = True,null = True,verbose_name="Rasm")
    slug = models.SlugField(unique=True, max_length=100)


    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        return super(Post, self).save(*args, **kwargs)
    class Meta:
        ordering = ['-created_date']


class Comment(models.Model):
    post=models.ForeignKey(Post,on_delete=models.CASCADE,verbose_name='Posts',related_name='comments')
    comment_author = models.CharField(max_length = 50,verbose_name = "Author")
    comment_content = models.CharField(max_length = 200,verbose_name = "content")
    comment_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.comment_content
    
    class Meta:
        ordering = ['-comment_date']

user/models.py
from django.db import models

# Create your models here.

post/forms.py
from django import forms
from django.forms import fields
from .models import Post

class PostForm(forms.ModelForm):
    class Meta :
        model=Post
        fields=['title','content','post_image']

user/forms.py
from django import forms

class LoginForm(forms.Form):
    username = forms.CharField(label = "Login")
    password = forms.CharField(label = "Password",widget = forms.PasswordInput)


class RegisterForm(forms.Form):
    username = forms.CharField(max_length = 50,label = "Username")
    password = forms.CharField(max_length=20,label = "password",widget = forms.PasswordInput)
    confirm = forms.CharField(max_length=20,label ="pasword try",widget = forms.PasswordInput)
    
    def clean(self):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        confirm = self.cleaned_data.get("confirm")

        if password and confirm and password != confirm:
            raise forms.ValidationError("Passwords Do Not Match")

        values = {
            "username" : username,
            "password" : password
        }
        return values

post/views.py
from django.core.checks import messages
from post.forms import PostForm
from django.shortcuts import redirect, render,get_object_or_404,reverse
from .models import Post,Comment
from django.contrib.auth.decorators import login_required
from django.template.defaultfilters import slugify
from django.contrib import messages
# Create your views here.


def post(request):
    keyword=request.GET.get('keyword')

    if keyword:
        post=Post.objects.filter(title=keyword)
        return render(request,'post.html',{'post':post})
    post=Post.objects.all()
    return render(request,'post.html',{'post':post})


def index(request):
    return render(request,'index.html')


def about(request):
    return render(request,'about.html')



@login_required(login_url='user:login')
def dashboard(request):
    posts=Post.objects.filter(author=request.user)
    return render (request,'dashboard.html',{'posts':posts})


@login_required(login_url='user:login')
def addPost(request):
    form=PostForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        post=form.save(commit=False)
        post.slug=slugify(post.title)
        post.author=request.user
        post.save()
        messages.success(request,'Post created successfully')
        return redirect('post:dashboard')
    return render(request,'addpost.html',{'form':form})


@login_required(login_url='user:login')
def detail(request,slug):
    post=get_object_or_404(Post,slug=slug)
    comments=post.comments.all()
    context={
        'post':post,
        'comments':comments
    }
    return render(request,'detail.html',context)


@login_required(login_url='user:login')
def update(request,slug):

    post=get_object_or_404(Post,slug=slug)
    form=PostForm(request.POST or None,request.FILES or None,instance=post)
    if form.is_valid():
        post=form.save(commit=False)

        post.author=request.user
        post.save()

        messages.success(request,'Update')
        return redirect('post:dashboard')
    
    return render(request,'update.html',{'form':form})


@login_required(login_url='user:login')
def delete(request,slug):
    post=get_object_or_404(Post,slug=slug)

    post.delete()
    messages.success(request,'delete post')
    return redirect('post:dashboard')


def addCommit(request,slug):
    post=get_object_or_404(Post,slug=slug)

    if request.method=='POST':
        comment_author=request.POST.get('comment_author')
        comment_content=request.POST.get('comment_content')

        new_comment=Comment(comment_author=comment_author,comment_content=comment_content)
        new_comment.post=post
        new_comment.save()
    return redirect(reverse('post:detail',kwargs={'slug':slug}))

user/views.py
from django.shortcuts import render,redirect
from .forms import RegisterForm,LoginForm
from django.contrib import messages
from django.contrib.auth.models import User
from django.contrib.auth import login,authenticate,logout

# Create your views here.

def register(request):
    
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        newUser = User(username =username)
        newUser.set_password(password)

        newUser.save()
        login(request,newUser)
        messages.info(request,"...")

        return redirect("index")
    context = {
            "form" : form
        }
    return render(request,"register.html",context)




def loginUser(request):
    form = LoginForm(request.POST or None)

    context = {
        "form":form
    }

    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")

        user = authenticate(username = username,password = password)

        if user is None:
            messages.info(request,"Username or Password Incorrect")
            return render(request,"user/login.html",context)

        messages.success(request,"...")
        login(request,user,backend='django.contrib.auth.backends.ModelBackend')
        return redirect("index")
    return render(request,"user/login.html",context)

def logoutUser(request):
    logout(request)
    messages.success(request,'You have successfully  Logout')
    return redirect('index')

templates/about.html
{% extends 'base.html' %}
{% block content %}
<h3>About</h3>
<p>
    Hello everyone. My name is Ulugbek. I am a Backend programmer.
</p>
{% endblock %}

templates/addpost.html
{% extends 'base.html' %}
{% block content%}
{% load crispy_forms_tags %}
<div class="row">
<div class="col-md-6 offset-md-3">
<h3>Add Post</h3>
<hr>

<form method="POST" enctype="multipart/form-data">
{% csrf_token %}
{{form.media}}
{{form|crispy}}
<br>
<button type="submit" class="btn btn-danger" >add post</button>
</form>
</div>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" > 
    {% block title %}
    
    {% endblock %}
    
</head>
<body>
    {% include 'includes/navbar.html' %}
    <div style="margin-top: 100px; margin-bottom: 100px;" class="container"  >
    
    {% if messages %}
        {% for message in messages %}
            
            {% if message.tags == "info" %}
                <div class="alert alert-danger">{{message}}</div>
                {% else %}
                <div class="alert alert-{{ message.tags }}">{{ message }}</div>
            {% endif %}
                
        {% endfor %}
    {% endif %}
    {% block content %}
    
    {% endblock %}
        
    </div>
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="https://cdn.rawgit.com/google/code-prettify/master/loader/run_prettify.js"></script>
</body>
</html>

templates/dashboard.html
{% extends 'base.html' %}
{% block content %}
<h3>Control Panel</h3>
<hr>
<p>
    Welcome, <small>{{request.user.username}}</small>
</p>
<hr>
<a class="btn btn-danger"  href="{% url 'post:addpost' %}">Add post</a>
<hr>

{% if posts %}
    <table class="table">
<thead>
    <tr>
        <th scope="col" >id</th>
        <th scope="col" >Title</th>
        <th scope="col" >Author</th>
        <th scope="col" >Date</th>
        <th scope="col" >Update</th>
        <th scope="col" >Delete</th>
    </tr>
</thead>
<tbody>
    {% for post in posts %}
        <tr>
            <td scope="row">{{post.id}}</td>
            <td><a href="{% url 'post:detail' post.slug %}" >{{post.title}}</a></td>
            <td>{{post.author.username}}</td>
            <td>{{post.created_date}}</td>
            <td><a href="{% url 'post:update' post.slug  %}" class="btn btn-danger">Update</a></td>
            <td><a href="{% url 'post:delete'  post.slug %}" class="btn btn-danger">Delete</a></td>
        </tr>
    {% endfor %}
</tbody>
    </table>
    {% else %}
    <div class="alert alert-danger"> 
No Post
    </div>
{% endif %}
    
{% endblock %}

templates/detail.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
<!--Post Content Column-->
<div class="col-lg-8">
    <!--Title-->
    <h3 class="mt-4">
        {{post.title}}
    </h3>
    <!--Author-->
    <p class="lead" >
        {{post.author.username}} by created.
    </p>
    <hr>
    <!--Date/Time-->
    <p>{{post.created_date}}</p>
    <hr>
    <!--Image-->
    
    {% if post.post_image %}
        <img class="img-fluid rounded" src="{{post.post_image.url}}" alt="">
    {% endif %}

    <hr>
    <!--Post contend end-->
        <p class="lead" >
            {{post.content|safe}}
        </p>
        <hr>
        <h4>Comments</h4>
        
        {% if comments %}
        {% for comment in comments %}
            
       
        <div class="media mb-4">
            <div class="media-body">
                <h5 class="mt-0">{{ comment.comment_author}}</h5>
            {{comment.comment_date}} <br>
            {{comment.comment_content}}

            </div>

        </div>
        {% endfor %}

        {% else %}
        <div class ="alert alert-danger">
            NO comments
          </div>
        {% endif %}
        <div class="card my-4 container">
            <h5 class="card-header">Add comment:</h5>
            <div class="card-body">
              <form method = "post" action = "{% url 'post:comment' post.slug %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="formGroupExampleInput">Name</label>
                    <input name = "comment_author" type="text" class="form-control" id="formGroupExampleInput" placeholder="who are you ">
                  </div>
                <div class="form-group">
                    <label for="formGroupExampleInput">Commet</label>
                  <textarea name = "comment_content" class="form-control" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-danger my-3">Add</button>
              </form>
            </div>
          </div>
</div>
</div>
{% endblock %}

templates/includes/navbar.html
<nav class="navbar navbar-toggleable-md navbar-inverse fixed-top bg-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'index'  %}">Blog Post</a>
    
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'about' %}">About</a>
        </li>
        <li class="nav-item active">
            <a class="nav-link" href="{% url 'post:post'  %}">Posts</a>
        </li>
        
      </ul>

      <ul class="navbar-nav ml-auto">
      {% if request.user.is_authenticated %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'post:dashboard'  %}">Control Panel</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'user:logout'  %}">Logout</a>
      </li>
      {% else %}

      <li class="nav-item active">
        <a class="nav-link" href="{% url 'user:login'  %}">Login</a>
      </li>
      {% endif %}
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'user:register'  %}">Register</a>
      </li>
      
      </ul>
    </div>


</nav>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<div class="aa">
   <h3> Welcome to the Software Science Blog</h3>
        <p>As developers on this blog, you can share your 
            blog posts and help people.</p>
            <p>
                
                {% if request.user.is_authenticated %}
                Hello,welcome,{{request.user.username}}
                    {% else %}
                    please come in
                {% endif %}
                    
            </p>
</div>
{% endblock %}

templates/post.html
{% extends 'base.html' %}
{% block content %}
<div class="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-log-8">
<h3>Posts</h3>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-10 offset-md-3">
        <div class="col-log-8">
<form >
{% csrf_token %}
<input type="text" name = "keyword" class="input-sm" maxlength="64" placeholder="Sreach...">
<button type="submit" class="btn btn-danger">search</button>

</form>

        </div>
    </div>


</div>

{% if post %}
{% for posts in post %}
<div class="row">
    <div class="col-md-10 offset-md-3">
        <!--Post content -->
        <div class="col-log-8">
            <!--Title-->
            <a href="{% url 'post:detail' posts.slug %}" ><h2 class="mt-4" >{{posts.title}}</h2></a>

<!--Author-->
<p class="lead" >
    {{posts.author.username}} by create
</p>
<!--Date/Time-->
<p>{{posts.created_date}}</p>
<hr>
<!--Post image-->
{% if posts.post_image %}
      <a href="{% url 'post:detail' posts.slug %}"><img class="img-fluid rounded" src="{{posts.post_image.url}}" alt=""></a>
      {% endif %}

<hr>

    <!--Post content-->
    <p class="lead" >
        {{posts.content|safe|truncatewords:50}}
    </p>
    <a href="{% url 'post:detail' posts.slug %}" class="btn btn-danger my-3" >Davomi</a>
        </div></div></div>

{% endfor %}  
{% else %}
<div class ="row">
    
    <div class="col-md-10 offset-md-3">
        <div class="col-lg-8">
<div class = "alert alert-danger">
   NO POST
</div>
</div>
</div>
</div>
{% endif %}
    
{% endblock %}

templates/update.html
{% extends 'base.html' %}
{% block content %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Update Post</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">update</button>
        </form>
    </div>
  </div>
{% endblock %}

templates/user/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Login</h3>
        <hr>
<form method="post">
{% csrf_token %}

{{form | crispy}}
<br>
<button type="submit" class = "btn btn-danger" >Login</button>
</form>
</div>
</div>
{% endblock %}

templates/user/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<form method="POST">
{% csrf_token %}

{{form|crispy}}
<button type="submit"  >Login</button>
</form>
{% endblock %}